config/routes.rb
Autoshop::Application.routes.draw do

  root :to => 'main_users#index'

  resources :backcalls, :only => [:create, :index]

  devise_for :admins, :controllers => { :sessions => "sessions" }
  devise_for :users, :controllers => { :sessions => "sessions" }

  resources :products

  resources :searches, :only => [] do
    post 'search_by_products', :on => :collection
  end

  resources :orders, :except => [:new, :update, :edit]
  resources :shop_carts,:only => [:update,:destroy]
  match 'shop_cart' => "shop_carts#show", :as => 'shop_cart', :via => 'get'

  resources :groups, :only => :show
  resources :custom_views, :only => :index

  resources :companies, :only => :show do
    resources :groups, :only => :show do
      resources :products, :only => [:show,:index]
    end
  end

  match '/admin_panel' => 'admin_panel/users#index', :as => 'admin_users'

  namespace :admin_panel do
    resources :products, :companies , :groups, :users ,:admins, :custom_views
    resources :photos, :only => [:index, :destroy]
    resources :orders, :only => [:index,:show,:update,:edit]
    resources :backcalls, :only => [:index, :destroy, :update]
    resources :order_items, :only => [:create, :update,:destroy]
  end
end

app/controllers/shop_carts_controller.rb
class ShopCartsController < ApplicationController
  before_filter :check_cookies_valid

  def update
    if params[:id] and params[:delete_item]
      render :json => {:state => CartMethods.remove_item_from_list(cookies,params[:id])}
    elsif params[:id]
      render :json => {:state => CartMethods.add_item_to_list(cookies,params[:id],params[:order_item_attr])}
    else
      redirect_to :root
    end
  end

  def show
    @items_list = CartMethods.get_items_list(cookies)
  end

  def destroy
    CartMethods.clear_cart(cookies)
    redirect_to :root
  end

  protected

  def check_cookies_valid
    redirect_to :root if !CartMethods.cookies_valid?(cookies)
  end

end

app/helpers/shop_carts_helper.rb
module ShopCartsHelper

end

app/views/shop_carts/cart_items.html.haml
-items = $redis.hgetall(@authcookie)
-keys = $redis.hkeys(@authcookie)

#order_items_table
  -if keys.count>0
    -price=0
    %p В корзине :
    %table#cart_table
      %tr
        %th.off Товар
        %th.off Количество
        %th.off Цена за еденицу
        %th.off Цена по позиции
        %th.off
        %th.off
        %th.off

      -keys.each do |key|
        - curr_ed_price = $redis.hget(key,'price').to_f()
        - curr_price = curr_ed_price*items[key].to_i()
        - price=price+curr_price;
        %tr{:id => "order_items_row#{key}", :class => "order_items_row"}
          %td.off
            =link_to($redis.hget(key,'name'),product_path(key))
          %td.off.count_of_order_item
            =items[key]
          %td.off.price_of_order_item
            =curr_ed_price
          %td.off.sum_price_of_order_item
            =curr_price.to_s()
          %td.off
            =link_to_function "+","addToCartTC('#{key}','#{1}')"
          %td.off
            =link_to_function "-","addToCartTC('#{key}','#{-1}')"
          %td.off
            =link_to_function "x","deleteCartItem('#{key}')"
      %tr.up_border
        %td.off
          Всего :
        %td.off
        %td.off
        %td.off#order_common_price=price.to_s()

    %br
    -if user_signed_in?
      = link_to 'Оформить',accept_order_path(:id),:id=>'accept_order'
      = link_to 'Отменить',cancel_order_path(:id),:id=>'cancel_order'

app/views/shop_carts/index.html.haml
-items = $redis.hgetall(@authcookie)
-keys = $redis.hkeys(@authcookie)


-if keys.count>0
  -price=0
  %p В корзине :
  %table#cart_table
    %tr
      %th.off Товар
      %th.off Количество
      %th.off Цена
      %th.off
      %th.off
      %th.off

    -keys.each do |key|
      - curr_price = $redis.hget(key,'price').to_f()*items[key].to_i()
      - price=price+curr_price;
      %tr
        %td.off
          =link_to($redis.hget(key,'name'),product_path(key))
        %td.off
          =items[key]
        %td.off
          =curr_price.to_s()
        %td.off
          =link_to_function "+","addToCart('#{key}','#{1}')"
        %td.off
          =link_to_function "-","addToCart('#{key}','#{-1}')"
        %td.off
          =link_to_function "x","deleteCartItem('#{key}')"
    %tr.up_border
      %td.off
        Всего :
      %td.off
      %td.off=price.to_s()

  %br
  -if user_signed_in?
    = link_to 'Оформить',accept_order_path(:id),:id=>'accept_order'
    = link_to 'Отменить',cancel_order_path(:id),:id=>'cancel_order'

app/views/shop_carts/shop_cart_info.html.haml
%p#order_pos_count Позиций : #{@auth_cookie_items_count}
%p#order_sum Сумма : #{order_summ()}

app/views/shop_carts/show.html.haml
.centerprod
  #order_items_table
    -if @items_list.count>0
      -price=0
      %p В корзине :
      %table#cart_table
        %tr
          %th.off Товар
          %th.off Количество
          %th.off Цена за еденицу
          %th.off Цена по позиции
          %th.off
          %th.off
          %th.off

        -@items_list.each do |key,item|
          - curr_ed_price = item['product_price'].to_f
          - curr_price = curr_ed_price*item['count'].to_i
          - price=price+curr_price
          - title = item['product_name']
          %tr{:id => "order_items_row#{key}", :class => "order_items_row"}
            %td.off
              =link_to(title,product_path(key))
            %td.off.count_of_order_item
              =item['count']
            %td.off.price_of_order_item
              =item['product_price']
            %td.off.sum_price_of_order_item
              =curr_price.to_s
            %td.off
              =link_to_function "+","addToCart('#{key}','1','#{title}','#{curr_ed_price}')"
            %td.off
              =link_to_function "-","addToCart('#{key}','-1','#{title}','#{curr_ed_price}')"
            %td.off
              =link_to_function "x","deleteCartItem('#{key}')"
        %tr.up_border
          %td.off
            Всего :
          %td.off
          %td.off
          %td.off#order_common_price=price.to_s

      %br
        .cart_control_links
          = link_to 'Оформить',orders_path,:method =>"post"
          = link_to 'Отменить',shop_cart_path(:id),:method => "delete"
    -else
      Корзина пуста...