config/routes.rb
Autoshop::Application.routes.draw do

  root :to => 'main_users#index'

  resources :backcalls, :only => [:create, :index]

  devise_for :admins, :controllers => { :sessions => "sessions" }
  devise_for :users, :controllers => { :sessions => "sessions" }

  resources :products

  resources :searches, :only => [] do
    post 'search_by_products', :on => :collection
  end

  resources :orders, :except => [:new, :update, :edit]
  resources :shop_carts,:only => [:update,:destroy]
  match 'shop_cart' => "shop_carts#show", :as => 'shop_cart', :via => 'get'

  resources :groups, :only => :show
  resources :custom_views, :only => :index

  resources :companies, :only => :show do
    resources :groups, :only => :show do
      resources :products, :only => [:show,:index]
    end
  end

  match '/admin_panel' => 'admin_panel/users#index', :as => 'admin_users'

  namespace :admin_panel do
    resources :products, :companies , :groups, :users ,:admins, :custom_views
    resources :photos, :only => [:index, :destroy]
    resources :orders, :only => [:index,:show,:update,:edit]
    resources :backcalls, :only => [:index, :destroy, :update]
    resources :order_items, :only => [:create, :update,:destroy]
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search_by_products
    @search_req = params[:search][:req].gsub('%','\%').gsub('_','\_')
    @products = Product.includes(:company,:group,:photos).where("lower(title) like ?" , "%#{@search_req.downcase}%").all
  end
end

app/views/searches/search_by_products.html.haml
.centerprod
  %h6.title Результаты запроса : #{@search_req}

  -if @products.length>0

    %table#tablecontent.table
      %tr
        %th.first
        %th
        %th
        %th.last

      - @products.each do |product|
        %tr
          %td.offset=(product.photos.first ?  (image_tag product.photos.first.photo.url(:thumb)) : (image_tag ('/assets/noimage.png')))
          %td.offset=link_to_function "Добавить в корзину", "addToCart('#{product.id}','1','#{product.title}','#{product.price}')"
          %td.offset=link_to product.title,company_group_product_path(product.company,product.group,product)
          %td=raw truncate_html(product.description)
  -else
    %p Ничего не найдено